/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdRouteImport } from './routes/$id'
import { Route as GraphqlRouteImport } from './routes/graphql'
import { Route as IdAvifRouteImport } from './routes/$id/avif'
import { Route as IdOriginalRouteImport } from './routes/$id/original'
import { Route as IdWebpRouteImport } from './routes/$id/webp'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as ImgFilenameRouteImport } from './routes/img/$filename'
import { Route as SettingsTokensRouteImport } from './routes/settings.tokens'
import { Route as ApiSettingsTokensRouteImport } from './routes/api.settings.tokens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlRoute = GraphqlRouteImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const IdAvifRoute = IdAvifRouteImport.update({
  id: '/avif',
  path: '/avif',
  getParentRoute: () => IdRoute,
} as any)
const IdOriginalRoute = IdOriginalRouteImport.update({
  id: '/original',
  path: '/original',
  getParentRoute: () => IdRoute,
} as any)
const IdWebpRoute = IdWebpRouteImport.update({
  id: '/webp',
  path: '/webp',
  getParentRoute: () => IdRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgFilenameRoute = ImgFilenameRouteImport.update({
  id: '/img/$filename',
  path: '/img/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsTokensRoute = ApiSettingsTokensRouteImport.update({
  id: '/api/settings/tokens',
  path: '/api/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/graphql': typeof GraphqlRoute
  '/$id/avif': typeof IdAvifRoute
  '/$id/original': typeof IdOriginalRoute
  '/$id/webp': typeof IdWebpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/img/$filename': typeof ImgFilenameRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/api/settings/tokens': typeof ApiSettingsTokensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/graphql': typeof GraphqlRoute
  '/$id/avif': typeof IdAvifRoute
  '/$id/original': typeof IdOriginalRoute
  '/$id/webp': typeof IdWebpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/img/$filename': typeof ImgFilenameRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/api/settings/tokens': typeof ApiSettingsTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/graphql': typeof GraphqlRoute
  '/$id/avif': typeof IdAvifRoute
  '/$id/original': typeof IdOriginalRoute
  '/$id/webp': typeof IdWebpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/img/$filename': typeof ImgFilenameRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/api/settings/tokens': typeof ApiSettingsTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/graphql'
    | '/$id/avif'
    | '/$id/original'
    | '/$id/webp'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/img/$filename'
    | '/settings/tokens'
    | '/api/settings/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$id'
    | '/graphql'
    | '/$id/avif'
    | '/$id/original'
    | '/$id/webp'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/img/$filename'
    | '/settings/tokens'
    | '/api/settings/tokens'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/graphql'
    | '/$id/avif'
    | '/$id/original'
    | '/$id/webp'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/img/$filename'
    | '/settings/tokens'
    | '/api/settings/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRouteWithChildren
  GraphqlRoute: typeof GraphqlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ImgFilenameRoute: typeof ImgFilenameRoute
  SettingsTokensRoute: typeof SettingsTokensRoute
  ApiSettingsTokensRoute: typeof ApiSettingsTokensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql': {
      id: '/graphql'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/avif': {
      id: '/$id/avif'
      path: '/avif'
      fullPath: '/$id/avif'
      preLoaderRoute: typeof IdAvifRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/original': {
      id: '/$id/original'
      path: '/original'
      fullPath: '/$id/original'
      preLoaderRoute: typeof IdOriginalRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/webp': {
      id: '/$id/webp'
      path: '/webp'
      fullPath: '/$id/webp'
      preLoaderRoute: typeof IdWebpRouteImport
      parentRoute: typeof IdRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$filename': {
      id: '/img/$filename'
      path: '/img/$filename'
      fullPath: '/img/$filename'
      preLoaderRoute: typeof ImgFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/tokens': {
      id: '/api/settings/tokens'
      path: '/api/settings/tokens'
      fullPath: '/api/settings/tokens'
      preLoaderRoute: typeof ApiSettingsTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IdRouteChildren {
  IdAvifRoute: typeof IdAvifRoute
  IdOriginalRoute: typeof IdOriginalRoute
  IdWebpRoute: typeof IdWebpRoute
}

const IdRouteChildren: IdRouteChildren = {
  IdAvifRoute: IdAvifRoute,
  IdOriginalRoute: IdOriginalRoute,
  IdWebpRoute: IdWebpRoute,
}

const IdRouteWithChildren = IdRoute._addFileChildren(IdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRouteWithChildren,
  GraphqlRoute: GraphqlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ImgFilenameRoute: ImgFilenameRoute,
  SettingsTokensRoute: SettingsTokensRoute,
  ApiSettingsTokensRoute: ApiSettingsTokensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
