/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraphqlRouteImport } from './routes/graphql'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImgFilenameRouteImport } from './routes/img/$filename'
import { Route as IdWebpRouteImport } from './routes/$id/webp'
import { Route as IdOriginalRouteImport } from './routes/$id/original'
import { Route as IdAvifRouteImport } from './routes/$id/avif'

const GraphqlRoute = GraphqlRouteImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgFilenameRoute = ImgFilenameRouteImport.update({
  id: '/img/$filename',
  path: '/img/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const IdWebpRoute = IdWebpRouteImport.update({
  id: '/webp',
  path: '/webp',
  getParentRoute: () => IdRoute,
} as any)
const IdOriginalRoute = IdOriginalRouteImport.update({
  id: '/original',
  path: '/original',
  getParentRoute: () => IdRoute,
} as any)
const IdAvifRoute = IdAvifRouteImport.update({
  id: '/avif',
  path: '/avif',
  getParentRoute: () => IdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/graphql': typeof GraphqlRoute
  '/$id/avif': typeof IdAvifRoute
  '/$id/original': typeof IdOriginalRoute
  '/$id/webp': typeof IdWebpRoute
  '/img/$filename': typeof ImgFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/graphql': typeof GraphqlRoute
  '/$id/avif': typeof IdAvifRoute
  '/$id/original': typeof IdOriginalRoute
  '/$id/webp': typeof IdWebpRoute
  '/img/$filename': typeof ImgFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRouteWithChildren
  '/graphql': typeof GraphqlRoute
  '/$id/avif': typeof IdAvifRoute
  '/$id/original': typeof IdOriginalRoute
  '/$id/webp': typeof IdWebpRoute
  '/img/$filename': typeof ImgFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/graphql'
    | '/$id/avif'
    | '/$id/original'
    | '/$id/webp'
    | '/img/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$id'
    | '/graphql'
    | '/$id/avif'
    | '/$id/original'
    | '/$id/webp'
    | '/img/$filename'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/graphql'
    | '/$id/avif'
    | '/$id/original'
    | '/$id/webp'
    | '/img/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRouteWithChildren
  GraphqlRoute: typeof GraphqlRoute
  ImgFilenameRoute: typeof ImgFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/graphql': {
      id: '/graphql'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$filename': {
      id: '/img/$filename'
      path: '/img/$filename'
      fullPath: '/img/$filename'
      preLoaderRoute: typeof ImgFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/webp': {
      id: '/$id/webp'
      path: '/webp'
      fullPath: '/$id/webp'
      preLoaderRoute: typeof IdWebpRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/original': {
      id: '/$id/original'
      path: '/original'
      fullPath: '/$id/original'
      preLoaderRoute: typeof IdOriginalRouteImport
      parentRoute: typeof IdRoute
    }
    '/$id/avif': {
      id: '/$id/avif'
      path: '/avif'
      fullPath: '/$id/avif'
      preLoaderRoute: typeof IdAvifRouteImport
      parentRoute: typeof IdRoute
    }
  }
}

interface IdRouteChildren {
  IdAvifRoute: typeof IdAvifRoute
  IdOriginalRoute: typeof IdOriginalRoute
  IdWebpRoute: typeof IdWebpRoute
}

const IdRouteChildren: IdRouteChildren = {
  IdAvifRoute: IdAvifRoute,
  IdOriginalRoute: IdOriginalRoute,
  IdWebpRoute: IdWebpRoute,
}

const IdRouteWithChildren = IdRoute._addFileChildren(IdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRouteWithChildren,
  GraphqlRoute: GraphqlRoute,
  ImgFilenameRoute: ImgFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
