catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

packages:
  - apps/*
  - packages/*

overrides:
  chokidar: ^5.0.0
  graphql: 17.0.0-alpha.9

catalog:
  "@antfu/eslint-config": ^6.0.0
  "@catppuccin/palette": ^1.7.1
  "@envelop/graphql-jit": ^11.0.0
  "@fontsource-variable/gabarito": ^5.1.1
  "@fontsource-variable/noto-sans-jp": ^5.1.1
  "@graphql-yoga/plugin-apq": ^3.8.0
  "@libsql/client": ^0.17.0
  "@nanostores/vue": ^1.0.0
  "@nuxt/devtools": ^3.0.0
  "@pothos/core": ^4.3.0
  "@pothos/plugin-relay": ^4.3.0
  "@sveltejs/adapter-node": ^5.2.9
  "@sveltejs/kit": ^2.49.5
  "@sveltejs/vite-plugin-svelte": ^6.0.0
  "@types/node": ^24.0.0
  "@urql/core": ^6.0.0
  "@urql/exchange-graphcache": ^8.0.0
  "@urql/svelte": ^5.0.0
  "@urql/vue": ^2.0.0
  autoprefixer: ^10.4.20
  dotenv: ^17.0.0
  drizzle-kit: ^0.31.0
  drizzle-orm: ^0.45.0
  eslint: ^9.14.0
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-svelte: ^3.12.5
  file-type: ^21.0.0
  graphql: ^17.0.0-alpha
  graphql-yoga: ^5.8.0
  husky: ^9.1.6
  lint-staged: ^16.2.5
  lucide-svelte: ^0.562.0
  lucide-vue-next: ^0.562.0
  modern-normalize: ^3.0.1
  nanostores: ^1.0.0
  nuxt: ^4.0.0
  nx: 22.4.1
  postcss: ^8.4.47
  postcss-load-config: ^6.0.1
  sass-embedded: ^1.83.0
  sharp: ^0.34.0
  solid-element: ^1.9.1
  solid-js: ^1.9.3
  stylelint: ^17.0.0
  stylelint-config-standard-scss: ^17.0.0
  svelte: ^5.46.4
  svelte-check: ^4.0.5
  tslib: ^2.8.1
  typescript: ^5.6.3
  typescript-eslint: ^8.12.2
  vite: ^7.0.0
  vite-plugin-monkey: ^7.0.0
  vite-plugin-solid: ^2.10.2
  zod: ^4.0.0
